import {slides,chapters} from './slides.js';
import {svg,esc,num} from './charts.js';
import {coverMarkup,coverFigure} from './cover.js';
import {titleFor,headlineFor,summaryTable,metadataFor} from './presentation.js';
import {exportChart,saveBlob,themeMarkup} from './export.js';

const $=s=>document.querySelector(s);
const icon=name=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${({download:'<path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/>',full:'<path d="M9 3H3v6m12-6h6v6M3 15v6h6m12-6v6h-6"/>'})[name]}</svg>`;
const states=Object.fromEntries(slides.map(s=>[s.id,Object.fromEntries(s.controls.map(c=>[c.key,c.initial]))]));
let bundle,index=0,mode='story',theme='dark',exportTheme='auto',returnMode='present',toastTimer,scrollFrame,scrollLock=false,narrow=matchMedia('(max-width:820px)').matches,dialogIndex=0;
let cleanup=()=>{};
const sceneNumber=i=>String(i+1).padStart(2,'0');
const stateFor=i=>states[slides[i].id];
function getView(i=index){
 const view=slides[i].render(bundle.tables,stateFor(i));
 if(i===0)return {...view,body:coverFigure(),chartTitle:'เบาหวานระยะสงบ: จากหลักฐานสู่ระบบบริการ',summary:'ผลการวิเคราะห์ข้อมูลโครงการ 995 คน จาก 20 หน่วยบริการ และข้อเสนอเชิงนโยบายจากการสัมภาษณ์ 9 พื้นที่',note:'ข้อเสนอฉบับร่างเพื่ออภิปราย อ้างอิงข้อมูลสรุปจาก notebook วิเคราะห์และร่างข้อเสนอเชิงนโยบาย',source:['notebook','policy'],rows:[{ชุดข้อมูล:'โครงการ',จำนวนผู้ป่วย:995,หน่วยบริการ:20},{ชุดข้อมูล:'สัมภาษณ์',ผู้ให้ข้อมูล:89,พื้นที่:9}]};
 return view;
}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500);}
function readURL(){const p=new URLSearchParams(location.search);const id=location.hash.slice(1)||p.get('scene');const found=slides.findIndex(s=>s.id===id);index=found<0?0:found;mode=['present','explore'].includes(p.get('mode'))?p.get('mode'):'story';theme=p.get('theme')==='light'?'light':'dark';exportTheme=['light','dark'].includes(p.get('export-theme'))?p.get('export-theme'):'auto';Object.assign(stateFor(index),Object.fromEntries(slides[index].controls.map(c=>[c.key,c.initial])));for(const c of slides[index].controls){if(!p.has(c.key))continue;const value=p.get(c.key);if(c.type==='checkbox')stateFor(index)[c.key]=value==='true';else if(c.options.some(o=>o[0]===value))stateFor(index)[c.key]=value;}}
function persist(push=false){const p=new URLSearchParams();if(mode!=='story')p.set('mode',mode);if(theme==='light')p.set('theme',theme);if(exportTheme!=='auto')p.set('export-theme',exportTheme);for(const c of slides[index].controls){const value=stateFor(index)[c.key];if(value!==c.initial)p.set(c.key,String(value));}const url=`${location.pathname}${p.size?'?'+p:''}#${slides[index].id}`;history[push?'pushState':'replaceState'](null,'',url);}
function sourceText(keys){return keys.map(key=>key==='notebook'?bundle.meta.notebook:key==='policy'?bundle.meta.policy:bundle.sources[key].file).join(' · ');}
function topbar(){document.body.className=`mode-${mode}`;document.documentElement.dataset.theme=theme;document.querySelector('meta[name="theme-color"]').content=theme==='light'?'#ffffff':'#0a0e14';const themeButton=$('#display-theme');themeButton.setAttribute('aria-label',theme==='light'?'โหมดมืด':'โหมดสว่าง');themeButton.title=theme==='light'?'เปิดโหมดมืด':'เปิดโหมดสว่าง';themeButton.querySelector('.theme-symbol').textContent=theme==='light'?'☾':'☀';themeButton.querySelector('.theme-label').textContent=theme==='light'?'โหมดมืด':'โหมดสว่าง';document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));$('#chapter-name').textContent=`ตอน ${String.fromCharCode(65+slides[index].chapter)} · ${chapters[slides[index].chapter]}`;$('#slide-number').textContent=`หน้า ${index+1} จาก ${slides.length}`;document.title=`${titleFor(slides[index].id)} · เบาหวานระยะสงบ`;}
function sceneText(i,view,heading='h2'){
 const s=slides[i];return `<div class="scene__text"><div class="scene__kicker"><span>ตอน ${String.fromCharCode(65+s.chapter)} · ${chapters[s.chapter]}</span><span>หน้า ${i+1} จาก ${slides.length}</span></div><${heading} class="scene__title" ${heading==='h1'?'id="slide-title" tabindex="-1"':''}>${esc(titleFor(slides[i].id))}</${heading}><p class="scene__headline">${esc(headlineFor(s.id,view,stateFor(i)))}</p><p class="scene__body">${esc(s.lead)}</p><div class="scene__data-summary">${summaryTable(s.id,view,stateFor(i))}</div><ul class="scene__caveats"><li>${esc(view.note)}</li></ul></div>`;
}
function controls(i){return slides[i].controls.map(c=>c.type==='checkbox'?`<label class="field field--check"><input type="checkbox" data-control="${c.key}" ${stateFor(i)[c.key]?'checked':''}>${esc(c.label)}</label>`:`<label class="field">${esc(c.label)}<select data-control="${c.key}" aria-label="${esc(c.label)}">${c.options.map(([v,label])=>`<option value="${esc(v)}" ${stateFor(i)[c.key]===v?'selected':''}>${esc(label)}</option>`).join('')}</select></label>`).join('');}
function clinicalControls(i){
 if(slides[i].id!=='clinical'||mode==='explore')return '';
 const labels={all:'ภาพรวม',compare:'เปรียบเทียบสองกลุ่ม',gt65:'> 6.5%',le65:'≤ 6.5%'};
 return `<div class="chart-controls" role="group" aria-label="กลุ่มตาม HbA1c ตั้งต้น"><span class="chart-controls__label">HbA1c ตั้งต้น</span><div class="chart-controls__options">${Object.entries(labels).map(([value,label])=>`<button class="btn btn--ghost" data-action="clinical-population" data-index="${i}" data-population="${value}" aria-pressed="${stateFor(i).population===value}" aria-label="${value==='gt65'||value==='le65'?'HbA1c ตั้งต้น ':''}${label}">${label}</button>`).join('')}</div></div>`;
}
function stage(i,view){if(i===0)return themeMarkup(coverMarkup(),theme);return `<div class="chart-shell"><h2 class="chart-heading"><span>${esc(view.chartTitle)}</span><button class="btn btn--icon btn--ghost" data-action="expand" data-index="${i}" aria-label="ขยายกราฟ" title="ขยายกราฟ">${icon('full')}</button></h2>${clinicalControls(i)}<div class="figure-slot">${themeMarkup(svg(view.body,view.summary),theme)}</div><p class="stage-caption">${esc(view.note)}</p></div>`;}
function selectClinicalPopulation(i,population,anchorTop){
 const control=slides[i].controls.find(c=>c.key==='population');
 if(slides[i].id!=='clinical'||!control.options.some(([value])=>value===population))return;
 stateFor(i).population=population;
 const v=getView(i);let figure;
 if(mode==='story'){
  activateStory(i);
  const scene=$(`#scene-${slides[i].id}`);
  scene.querySelector('.scene__text').outerHTML=sceneText(i,v);
  figure=narrow?scene.querySelector('[data-figure]'):$('#chart-stage');
 }else{
  figure=$('#chart-stage');
  $('.present .scene__text').outerHTML=sceneText(i,v,'h1');
  $('.present .ribbon').innerHTML=ribbon(i,v);
 }
 figure.innerHTML=stage(i,v);$('#tooltip').hidden=true;persist();
 const selected=figure.querySelector(`[data-population="${population}"]`);
 selected.focus({preventScroll:true});
 if(mode==='story'||narrow)window.scrollBy({top:selected.getBoundingClientRect().top-anchorTop,behavior:'instant'});
}
function actions(i,{explore=true}={}){return `<div class="ribbon__actions"><button class="btn btn--ghost" data-action="source" data-index="${i}">ที่มาและวิธีคำนวณ</button>${explore?`<button class="btn btn--ghost" data-action="explore" data-index="${i}">สำรวจข้อมูลในภาพ</button>`:''}<button class="btn btn--ghost" data-action="download-png" data-index="${i}">${icon('download')} ดาวน์โหลดภาพ</button><button class="btn btn--icon btn--ghost" data-action="export-options" data-index="${i}" aria-label="รูปแบบไฟล์และพื้นหลังภาพ" title="รูปแบบไฟล์และพื้นหลังภาพ">⋯</button></div>`;}
function ribbon(i,view,withActions=true){const m=metadataFor(slides[i].id,view,stateFor(i));return `<div class="ribbon__meta"><span class="ribbon__item"><b>ช่วงเวลา</b> ${esc(m.time)}</span><span class="ribbon__item"><b>ขอบเขต</b> ${esc(m.scope)}</span><span class="ribbon__item"><b>ตัวชี้วัด</b> ${esc(m.measure)}</span><span class="badge ${m.evidence==='ข้อเสนอเพื่อหารือ'?'badge--discussion':''}" title="${esc(m.discussion)}">${esc(m.evidence)}</span></div>${withActions?actions(i):''}`;}
function dataTable(view){const keys=Object.keys(view.rows[0]||{});return `<div class="table-wrap"><table class="data-table"><thead><tr>${keys.map(k=>`<th scope="col">${esc(k)}</th>`).join('')}</tr></thead><tbody>${view.rows.map(row=>`<tr>${keys.map(k=>`<td class="${typeof row[k]==='number'?'num':''}">${esc(typeof row[k]==='number'?(Number.isInteger(row[k])?row[k]:Number(row[k].toPrecision(6))):row[k])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function present(){const v=getView(),overview=['evidence','policy','pathway','next'].includes(slides[index].id);$('#main').innerHTML=`<div class="present"><div class="present__progress" role="progressbar" aria-label="ความคืบหน้าการนำเสนอ" aria-valuemin="0" aria-valuemax="${slides.length}" aria-valuenow="${index+1}"><span style="width:${index/(slides.length-1)*100}%"></span></div><article class="scene ${index===0?'scene--cover':''}" data-scene="${slides[index].id}" data-layout="${overview?'overview':'chart'}"><div class="scene__stage" id="chart-stage">${stage(index,v)}</div>${index===0?'':sceneText(index,v,'h1')}<footer class="ribbon">${index===0?actions(index,{explore:false}):ribbon(index,v)}</footer></article></div><nav class="present__nav" aria-label="เปลี่ยนสไลด์"><button id="previous" class="btn btn--nav" aria-label="สไลด์ก่อนหน้า" ${index===0?'disabled':''}>‹</button><button id="next" class="btn btn--nav" aria-label="สไลด์ถัดไป" ${index===slides.length-1?'disabled':''}>›</button></nav>`;}
function explore(){const v=getView();$('#main').innerHTML=`<div class="explore"><div class="explore__bar"><label class="field">ภาพที่ต้องการสำรวจ<select id="scene-select" aria-label="ภาพที่ต้องการสำรวจ">${slides.map((s,i)=>`<option value="${i}" ${i===index?'selected':''}>${sceneNumber(i)} · ${esc(titleFor(slides[i].id))}</option>`).join('')}</select></label>${controls(index)}<button class="btn" data-action="return">${returnMode==='story'?'กลับไปอ่านเนื้อหา':'กลับไปนำเสนอ'}</button></div><div class="explore__main"><div class="scene__stage explore__stage" id="chart-stage">${stage(index,v)}</div><aside class="explore__side">${sceneText(index,v,'h1')}<div class="explore__actions">${actions(index,{explore:false})}</div></aside></div><footer class="ribbon" id="explore-ribbon">${ribbon(index,v,false)}</footer><section class="explore__table"><div class="explore__tablehead"><h2>ข้อมูลที่แสดงในภาพ</h2><button class="btn btn--ghost" data-action="csv" data-index="${index}">ดาวน์โหลด CSV</button></div><div id="explore-table">${dataTable(v)}</div></section></div>`;}
function updateExplore(){const v=getView();$('#chart-stage').innerHTML=stage(index,v);$('.explore__side').innerHTML=sceneText(index,v,'h1')+`<div class="explore__actions">${actions(index,{explore:false})}</div>`;$('#explore-ribbon').innerHTML=ribbon(index,v,false);$('#explore-table').innerHTML=dataTable(v);$('#tooltip').hidden=true;persist();}
function story(restore=false){
 const active=index;const intro=`<header class="story__intro"><p class="eyebrow">การประเมินผลโครงการและข้อเสนอเชิงนโยบาย</p><h1>เบาหวานระยะสงบ<br>จากหลักฐานสู่ระบบบริการ</h1><p class="story__question">ผลลัพธ์ที่พบชวนให้ปรับระบบบริการอย่างไร เพื่อให้การดูแลต่อเนื่อง ปลอดภัย และเป็นธรรม</p><p class="story__take">ข้อมูลโครงการแสดงความเป็นไปได้ของการลดภาระยา การขยายผลต้องพิจารณาความต่างของผู้ป่วย การติดตาม กำลังคน การจ่าย และข้อมูลไปพร้อมกัน</p><div class="story__cta"><button class="btn btn--primary" data-action="start">เริ่มนำเสนอ</button><button class="btn" data-action="explore" data-index="2">สำรวจข้อมูล</button></div><p class="chart-note">ที่มา: notebook วิเคราะห์ประสิทธิผล และ (ร่าง) ข้อเสนอเชิงนโยบาย</p><p class="chart-note">กราฟในโหมดอ่าน นำเสนอ และสำรวจ ใช้ข้อมูลชุดเดียวกัน</p></header>`;
 const blocks=slides.map((s,i)=>{const v=getView(i);return `<article class="story-scene" id="scene-${s.id}" data-index="${i}">${sceneText(i,v)}${narrow?`<div class="scene__stage story__inline" data-figure="${i}">${stage(i,v)}</div><div class="ribbon">${actions(i)}</div>`:`<div class="ribbon"><button class="linkbtn" data-action="source" data-index="${i}">ที่มาและวิธีคำนวณ</button><button class="linkbtn" data-action="explore" data-index="${i}">สำรวจข้อมูลในภาพ</button></div>`}<div class="story-step"><p><span class="scene__stepno">ประเด็นสำคัญ</span> ${esc(s.insight)}</p></div></article>`;}).join('');
 const v=getView(active);$('#main').innerHTML=`<div class="story">${intro}<div class="story__grid"><div class="story__text">${blocks}<footer class="story__end"><p>จบเรื่อง — กลับไปสำรวจหลักฐานหรือเปิดสไลด์สำหรับนำเสนอ</p><div class="story-end-link"><button class="btn" data-action="start">เริ่มนำเสนอ</button><button class="btn btn--ghost" data-action="top">กลับจุดเริ่มต้น</button></div></footer></div>${narrow?'':`<div class="story__sticky"><p class="story__stagehead" id="stage-head">${sceneNumber(active)} ${esc(titleFor(slides[active].id))}</p><div class="scene__stage story__stage" id="chart-stage">${stage(active,v)}</div><div class="story__ribbon" id="story-ribbon">${actions(active)}</div></div>`}</div></div>`;
 const onScroll=()=>{if(scrollFrame||scrollLock||$('#details').open)return;scrollFrame=requestAnimationFrame(()=>{scrollFrame=0;if(mode!=='story'||scrollLock)return;let next=0;for(const el of document.querySelectorAll('.story-scene')){if(el.getBoundingClientRect().top<innerHeight*.42)next=Number(el.dataset.index);else break;}activateStory(next);});};window.addEventListener('scroll',onScroll,{passive:true});cleanup=()=>{window.removeEventListener('scroll',onScroll);cancelAnimationFrame(scrollFrame);scrollFrame=0;};
 if(restore)requestAnimationFrame(()=>scrollToScene(active,false));
}
function activateStory(i){if(i===index)return;index=i;const v=getView();topbar();if(!narrow){$('#stage-head').textContent=`${sceneNumber(index)} ${titleFor(slides[index].id)}`;$('#chart-stage').innerHTML=stage(index,v);$('#story-ribbon').innerHTML=actions(index);}$('#tooltip').hidden=true;persist();}
function scrollToScene(i,smooth=true){scrollLock=true;index=i;topbar();const v=getView();if(!narrow){$('#stage-head').textContent=`${sceneNumber(i)} ${titleFor(slides[i].id)}`;$('#chart-stage').innerHTML=stage(i,v);$('#story-ribbon').innerHTML=actions(i);}const el=$(`#scene-${slides[i].id}`);el?.scrollIntoView({block:'start',behavior:smooth&&!matchMedia('(prefers-reduced-motion:reduce)').matches?'smooth':'instant'});setTimeout(()=>{scrollLock=false;},smooth?500:80);}
function mount({restore=false}={}){cleanup();cleanup=()=>{};$('#tooltip').hidden=true;topbar();if(mode==='present')present();else if(mode==='explore')explore();else story(restore);}
function go(i,push=true){if(i<0||i>=slides.length)return;if($('#details').open)$('#details').close();index=i;persist(push);if(mode==='story')scrollToScene(i);else{mount();window.scrollTo({top:0,behavior:'instant'});}}
function switchMode(next,{target=index,restore=true}={}){if(mode==='explore'&&next!=='explore')returnMode=next;if(next==='explore'&&mode!=='explore')returnMode=mode;index=target;mode=next;persist(true);mount({restore:next==='story'&&restore});if(next!=='story'||!restore)window.scrollTo({top:0,behavior:'instant'});}
function openDrawer(title,body,{wide=false}={}){const d=$('#details');d.classList.toggle('figure-dialog',wide);$('#drawer-title').textContent=title;$('#dialog-content').innerHTML=body;if(!d.open)d.showModal();d.scrollTop=0;}
function sources(i){dialogIndex=i;const v=getView(i);openDrawer('ที่มาและวิธีคำนวณ',`<h3>${esc(v.chartTitle)}</h3><p>${esc(v.note)}</p><p>${esc(slides[i].foot)}</p><h3>ข้อมูลตามตัวเลือกที่แสดง</h3>${dataTable(v)}<button class="btn" data-action="csv" data-index="${i}">ดาวน์โหลด CSV</button><h3>แหล่งข้อมูล</h3><p><code>${esc(sourceText(v.source))}</code></p><p>ตัวเลือกที่เปลี่ยนในโหมดสำรวจจะใช้ร่วมกับการอ่าน การนำเสนอ และภาพดาวน์โหลด</p>`);}
function expand(i){const v=getView(i);openDrawer(v.chartTitle,`<p class="chart-note">เลื่อนกราฟแนวนอนบนจอเล็กเพื่ออ่านรายละเอียด</p><div class="expanded-figure">${themeMarkup(svg(v.body,v.summary),theme)}</div><p>${esc(v.note)}</p>${actions(i)}`,{wide:true});}
function exportOptions(i){dialogIndex=i;const v=getView(i);openDrawer('ดาวน์โหลดภาพ',`<h3>${esc(v.chartTitle)}</h3><p>ภาพจะใช้ตัวเลือกปัจจุบัน พร้อมชื่อกราฟ หมายเหตุ และแหล่งข้อมูล</p><label class="field">พื้นหลังภาพ<select id="export-theme" aria-label="พื้นหลังภาพดาวน์โหลด"><option value="auto" ${exportTheme==='auto'?'selected':''}>ตามโหมดหน้าจอ (${theme==='light'?'สว่าง':'มืด'})</option><option value="dark" ${exportTheme==='dark'?'selected':''}>พื้นหลังมืด</option><option value="light" ${exportTheme==='light'?'selected':''}>พื้นหลังสว่าง</option></select></label><div class="explore__actions"><button class="btn btn--primary" data-action="download-png" data-index="${i}">PNG · 2,400 px</button><button class="btn" data-action="download-svg" data-index="${i}">SVG · เวกเตอร์</button></div><p>ไฟล์ SVG มีฟอนต์ Prompt ฝังอยู่ในภาพเพื่อรองรับข้อความภาษาไทย</p>`);}
function downloadCSV(i){const rows=getView(i).rows,keys=Object.keys(rows[0]||{});const cell=v=>'"'+String(v??'').replace(/"/g,'""')+'"';const csv=[keys.map(cell).join(','),...rows.map(r=>keys.map(k=>cell(r[k])).join(','))].join('\r\n');saveBlob(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}),`dmr-${slides[i].id}-selected.csv`);}
async function download(i,format,button){const v=getView(i);button.disabled=true;try{toast('กำลังเตรียมภาพตามตัวเลือกปัจจุบัน…');await exportChart({slide:slides[i],view:v,state:{...stateFor(i)},source:sourceText(v.source),index:i,total:slides.length,format,theme:exportTheme==='auto'?theme:exportTheme});toast(`ดาวน์โหลด ${format.toUpperCase()} แล้ว`);}catch(e){console.error(e);toast(e.message||'ดาวน์โหลดไม่สำเร็จ');}finally{button.disabled=false;}}
async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{toast('เบราว์เซอร์นี้ไม่รองรับการเปิดเต็มหน้าจอ');}}
function about(){openDrawer('วิธีอ่านและสารบัญ',`<p>อ่านเนื้อหาโดยเลื่อนหน้า กราฟด้านข้างจะเปลี่ยนตามเรื่อง บนมือถือจะแสดงกราฟใต้เนื้อหาแต่ละส่วน</p><p>โหมดนำเสนอ: กด ← / → หรือ Space เพื่อเปลี่ยนหน้า, F เพื่อเต็มจอ, E เพื่อสำรวจข้อมูล</p><p>เปลี่ยนตัวเลือกใน “สำรวจข้อมูล” แล้วกลับมานำเสนอได้ ภาพดาวน์โหลดใช้ค่าที่เลือกเดียวกัน</p><h3>สารบัญ</h3><ol class="toc">${slides.map((s,i)=>`<li><button class="linkbtn" data-action="goto" data-index="${i}">${sceneNumber(i)} · ${esc(titleFor(slides[i].id))}</button></li>`).join('')}</ol><h3>การออกแบบ</h3><p>ใช้โครงหน้าและรูปแบบการอ่าน–นำเสนอของ <a href="https://psitthirat.github.io/HRH-model/" target="_blank" rel="noopener noreferrer">HRH-model</a> เปลี่ยนสีหลักเป็นชมพูคอรัล และเพิ่มการดาวน์โหลดภาพในแต่ละสไลด์</p>`);}
function release(){openDrawer('ข้อมูลฉบับร่าง',`<h3>เบาหวานระยะสงบ: จากหลักฐานสู่ระบบบริการ</h3><p>สไลด์ ${slides.length} หน้า จากตารางสรุปผลวิเคราะห์และร่างข้อเสนอเชิงนโยบาย ใช้สำหรับอภิปราย</p><p><code>${esc(bundle.meta.notebook)}</code><br><code>${esc(bundle.meta.policy)}</code></p><h3>ข้อจำกัดที่ต้องอ่านร่วมกับผลลัพธ์</h3><p>เป็นข้อมูลสังเกตการณ์ ไม่ใช่การทดลองสุ่ม กลุ่มโครงการ ทะเบียน และสำรวจใช้เวลาและวิธีวัดต่างกัน การหยุดยาไม่เท่ากับการยืนยันภาวะเบาหวานระยะสงบ</p><p>แผนภาพข้อเสนอและเส้นทางบริการเป็นการสังเคราะห์เพื่อหารือ ไม่ใช่เกณฑ์รักษารายบุคคล</p><p>หน้าเว็บใช้เฉพาะข้อมูลสรุป ไม่มีข้อมูลผู้ป่วยรายบุคคล และไม่เรียกบริการภายนอกเพื่อแสดงกราฟ</p>`);}

document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b||!bundle)return;if(b.dataset.mode){if($('#details').open)$('#details').close();switchMode(b.dataset.mode);return;}const i=b.hasAttribute('data-index')?Number(b.dataset.index):index;const action=b.dataset.action;if(action==='clinical-population')selectClinicalPopulation(i,b.dataset.population,b.getBoundingClientRect().top);else if(action==='source')sources(i);else if(action==='expand')expand(i);else if(action==='export-options')exportOptions(i);else if(action==='download-png')download(i,'png',b);else if(action==='download-svg')download(i,'svg',b);else if(action==='csv')downloadCSV(i);else if(action==='explore'){if($('#details').open)$('#details').close();switchMode('explore',{target:i});}else if(action==='return')switchMode(returnMode);else if(action==='goto')go(i);else if(action==='start')switchMode('present',{target:0});else if(action==='top'){index=0;persist();mount();window.scrollTo({top:0,behavior:'smooth'});}else if(b.id==='next')go(index+1);else if(b.id==='previous')go(index-1);else if(b.id==='display-theme'){const y=window.scrollY;theme=theme==='light'?'dark':'light';persist(true);mount();window.scrollTo({top:y,behavior:'instant'});}else if(b.id==='fullscreen')fullscreen();else if(b.id==='about')about();else if(b.id==='release')release();else if(b.id==='close-dialog')$('#details').close();});
document.addEventListener('change',event=>{const el=event.target;if(el.dataset.control){stateFor(index)[el.dataset.control]=el.type==='checkbox'?el.checked:el.value;updateExplore();}else if(el.id==='scene-select')go(Number(el.value));else if(el.id==='export-theme'){exportTheme=el.value;persist();}});
document.addEventListener('keydown',event=>{if(!bundle||$('#details').open||event.ctrlKey||event.metaKey||event.altKey||event.target.closest('input,select,textarea,[contenteditable]'))return;if(event.key==='?'){about();return;}if(event.key===' '&&event.target.closest('button,a,[role=button]'))return;if(mode!=='present')return;if(['ArrowRight','PageDown',' '].includes(event.key)){event.preventDefault();go(index+1);}else if(['ArrowLeft','PageUp'].includes(event.key)){event.preventDefault();go(index-1);}else if(event.key==='Home'){event.preventDefault();go(0);}else if(event.key==='End'){event.preventDefault();go(slides.length-1);}else if(event.key.toLowerCase()==='f')fullscreen();else if(event.key.toLowerCase()==='e')switchMode('explore');});
$('#details').addEventListener('click',event=>{if(event.target!==$('#details'))return;const r=$('#details').getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)$('#details').close();});
window.addEventListener('popstate',()=>{if(!bundle)return;readURL();mount({restore:!!location.hash});});
matchMedia('(max-width:820px)').addEventListener('change',event=>{narrow=event.matches;if(bundle&&mode==='story')mount({restore:!!location.hash});});
function showTooltip(mark,x,y){const el=$('#tooltip');el.textContent=mark.dataset.tip;el.hidden=false;el.style.left=Math.max(8,Math.min(x+12,innerWidth-el.offsetWidth-12))+'px';el.style.top=Math.max(8,Math.min(y+12,innerHeight-el.offsetHeight-12))+'px';}
document.addEventListener('click',event=>{const mark=event.target.closest('[data-tip]');if(mark){const r=mark.getBoundingClientRect();showTooltip(mark,event.clientX||r.right,event.clientY||r.top);}else $('#tooltip').hidden=true;});
document.addEventListener('pointerover',event=>{const mark=event.target.closest('[data-tip]');if(mark)showTooltip(mark,event.clientX,event.clientY);});
document.addEventListener('pointerout',event=>{if(event.target.closest('[data-tip]'))$('#tooltip').hidden=true;});
document.addEventListener('focusin',event=>{const mark=event.target.closest('[data-tip]');if(mark){const r=mark.getBoundingClientRect();showTooltip(mark,r.right,r.top);}});
document.addEventListener('focusout',()=>$('#tooltip').hidden=true);
document.addEventListener('keydown',event=>{if(event.key==='Escape')$('#tooltip').hidden=true;});
try{const r=await fetch('data/evidence.json');if(!r.ok)throw Error(`โหลดข้อมูลไม่สำเร็จ (${r.status})`);bundle=await r.json();await document.fonts.ready;readURL();mount({restore:!!location.hash||new URLSearchParams(location.search).has('scene')});}catch(e){$('#main').innerHTML=`<div class="loading"><h1>เปิดข้อมูลไม่ได้</h1><p>${esc(e.message)}</p><p>เปิดเว็บผ่าน localhost โดยใช้คำสั่งใน story/README.md</p></div>`;console.error(e);}
