import * as G from './charts.js';
const {num,signed,policies}=G;
const select=(key,label,options,initial)=>({key,label,options,initial:initial??options[0][0]});
const checkbox=(key,label,initial=true)=>({key,label,type:'checkbox',initial});
const metrics=[['HbA1c','HbA1c'],['FBS','น้ำตาลอดอาหาร (FBS)'],['BMI','BMI'],['Waist','รอบเอว']];
const units={HbA1c:'จุดร้อยละ',FBS:'mg/dL',BMI:'kg/m²',Waist:'cm'};
const timingText=value=>value.split(', ').map(part=>part.replace(/^assumed (\d+)$/, 'อนุมานจากแบบบันทึก $1 คู่').replace(/^labelled (\d+)$/, 'ระบุเดือนติดตาม $1 คู่').replace(/^measured (\d+)$/, 'มีวันที่ตรวจ $1 คู่')).join(' · ');
const result=(body,chartTitle,note,rows,source,badge,summary)=>({body,chartTitle,note,rows,source,badge,summary:summary||chartTitle});

export const slides=[
 {id:'opening',label:'จากคน สู่ระบบ',chapter:0,eyebrow:'A NEW POSSIBILITY',title:'เบาหวานระยะสงบ<br>เริ่มที่<em>คน</em><br>ไปต่อด้วย<em>ระบบ</em>',tag:'จากหลักฐาน สู่ข้อเสนอเชิงนโยบาย',lead:'เมื่อการหยุดยาเป็นไปได้ ระบบบริการต้องเปลี่ยนอย่างไร เพื่อให้โอกาสนั้นเกิดขึ้นอย่างปลอดภัย ต่อเนื่อง และเป็นธรรม',stats:[['995','คนในโครงการ'],['20','หน่วยบริการ']],insight:'เรื่องนี้เริ่มจากผลลัพธ์ของผู้ป่วย และชวนมองต่อถึงระบบที่ต้องรองรับการดูแลระยะยาว',foot:'หลักฐานจากการวิเคราะห์ข้อมูลโครงการและร่างข้อเสนอเชิงนโยบาย · ต้นแบบสำหรับอภิปราย',controls:[],render(T){const r=T.outcomes.find(r=>r.cohort==='Programme'&&r.outcome.startsWith('Drug cessation AT'));return result(G.opening(r.pct),'โอกาสที่มองเห็นได้จากข้อมูล','*เวลา 6 เดือนของข้อมูลยาส่วนใหญ่อนุมานจากแบบบันทึก • 13.4% เป็นอัตราหยุดยา ไม่ใช่อัตราระยะสงบที่ยืนยันแล้ว',[r],['outcomes'],'6 MONTHS','หยุดยาลดน้ำตาล 96 จาก 718 คน หรือ 13.4% ที่จุดติดตาม 6 เดือน');}},
 {id:'evidence',label:'หลักฐานสามชุด สองมุม',chapter:0,eyebrow:'01 / THE EVIDENCE',title:'เรื่องเดียวกัน<br><em>หลักฐานหลายมุม</em>',lead:'ข้อมูลเชิงปริมาณบอกว่าเกิดอะไรขึ้น ส่วนเสียงจากพื้นที่ช่วยอธิบายว่าระบบบริการต้องทำอะไรต่อ',insight:'อ่านทั้งสาม cohort แยกกัน เพราะเวลา วิธีบันทึกยา และบริบทของผู้ป่วยต่างกัน',foot:'จำนวน cohort จาก notebook 02 และ README · การสัมภาษณ์จากบทนำของร่างข้อเสนอเชิงนโยบาย',controls:[],render(){return result(G.cohorts(),'ฐานข้อมูลที่ใช้เล่าเรื่อง','ทะเบียนเป็นชุดเปรียบเทียบจากโรงพยาบาลแห่งเดียว ไม่ใช่กลุ่มควบคุมแบบสุ่ม • 9 พื้นที่สัมภาษณ์ไม่ใช่ 20 หน่วยบริการของ cohort โครงการ',[{ชุดข้อมูล:'โครงการ',จำนวน:995,หน่วยบริการ:20,เวลา:'6 เดือน'},{ชุดข้อมูล:'ทะเบียน',จำนวน:1461,หน่วยบริการ:1,เวลา:'ห้องปฏิบัติการ 6 เดือน; ข้อมูลยาไม่มีวันที่'},{ชุดข้อมูล:'สำรวจ 2566',จำนวน:214,หน่วยบริการ:'เครือข่ายกระนวน',เวลา:'3 เดือน'},{ชุดข้อมูล:'สัมภาษณ์',จำนวน:89,หน่วยบริการ:9,เวลา:'เชิงคุณภาพ: บุคลากร 58; ผู้ป่วย 31'}],['notebook','policy'],'MIXED METHODS');}},
 {id:'outcomes',label:'หยุดยาได้ บอกอะไรเรา',chapter:1,eyebrow:'02 / THE FIRST SIGNAL',title:'<em>13.4%</em> หยุดยาได้<br>แต่เรื่องยังไม่จบ<br>ที่การหยุดยา',lead:'ในผู้ที่ประเมินการหยุดยาได้ 718 คน มี 96 คนหยุดยาลดน้ำตาลทั้งหมดที่จุดติดตาม 6 เดือน ลองเปลี่ยนผลลัพธ์เพื่อเห็นว่าแต่ละคำถามใช้ฐานคนต่างกัน',insight:'ข้อมูลยังไม่มีวันหยุดยา จึงยืนยันระยะเวลาปลอดยาไม่ได้ ตัวเลขระยะสงบต้องอ่านเป็น “ขอบเขตบน”',foot:'Notebook 02 §5 · table4_outcome_rates.csv · ช่วงความเชื่อมั่น 95% แบบ Wilson',controls:[select('outcome','ผลลัพธ์',[['cessation','หยุดยาลดน้ำตาลทั้งหมด'],['remission','ระยะสงบ — ขอบเขตบน'],['control','HbA1c < 7%']])],render(T,s){const key={cessation:'Drug cessation AT',remission:'Remission AT',control:'HbA1c < 7% at'}[s.outcome];const r=T.outcomes.find(r=>r.cohort==='Programme'&&r.outcome.startsWith(key));const name={cessation:'หยุดยาลดน้ำตาลทั้งหมด',remission:'ระยะสงบ: ขอบเขตบนที่ยังยืนยันไม่ได้',control:'ระดับ HbA1c ต่ำกว่า 7%'}[s.outcome];return result(G.waffle(r),name,s.outcome==='remission'?'HbA1c < 6.5% ร่วมกับไม่ใช้ยา แต่ไม่มีวันหยุดยาเพื่อยืนยันช่วงปลอดยา • ไม่ใช่อัตราระยะสงบที่ยืนยันแล้ว':'แต่ละผลลัพธ์มีเกณฑ์และข้อมูลที่ใช้ได้ต่างกัน จึงใช้ตัวหารต่างกัน • เวลา 6 เดือนส่วนใหญ่อนุมานจากแบบบันทึก',[r],['outcomes'],`n = ${r.n}`,`${name} ${num(r.pct)}%; ${r.events}/${r.n} คน`);}},
 {id:'remission',label:'หยุดยาและน้ำตาลถึงเกณฑ์',chapter:1,eyebrow:'03 / THE JOINT OUTCOME',title:'หยุดยาได้<br>พร้อมกับ<em>HbA1c < 6.5%</em>',lead:'พิจารณาสถานะยาและ HbA1c ร่วมกันที่จุดติดตาม 6 เดือน โดยแยกผู้ที่หยุดยาจากผู้ที่ไม่ใช้ยาตั้งแต่เริ่มโครงการ เพื่อให้เห็นว่าตัวเลขแต่ละฐานตอบคนละคำถาม',insight:'HbA1c < 6.5% และไม่ใช้ยาเป็นองค์ประกอบของระยะสงบ แต่ต้องมีผลตรวจอย่างน้อย 3 เดือนหลังหยุดยาเพื่อยืนยันด้วย',foot:'ผลลัพธ์ร่วมจากข้อมูลโครงการตามนิยามจุดติดตาม 6 เดือนใน notebook 02; 95% CI แบบ Wilson · ฉันทามติ remission: doi:10.2337/dci21-0034',controls:[select('basis','ฐานการประเมิน',[['stopped_controlled','ผู้ใช้ยาตั้งต้นที่มีผลติดตามครบ'],['among_stoppers','เฉพาะผู้หยุดยาที่มี HbA1c ติดตาม'],['all_off_drug_proxy','รวมผู้ไม่ใช้ยาตั้งแต่ต้น — นิยามเดิม']])],render(T,s){
  const r=T.remission_detail.find(r=>r.group===s.basis),all=s.basis==='all_off_drug_proxy',conditional=s.basis==='among_stoppers';
  const title=all?'ไม่ใช้ยาและ HbA1c < 6.5%: รวมผู้ไม่ใช้ยาตั้งแต่ต้น':conditional?'ในผู้หยุดยา: สัดส่วนที่ HbA1c < 6.5%':'หยุดยาลดน้ำตาลทั้งหมดและ HbA1c < 6.5%';
  const denominator=all?'ฐาน 790 คนมีข้อมูลยาและ HbA1c ติดตามครบ รวมผู้ไม่ใช้ยาตั้งต้น':conditional?'หยุดยาได้ 96 คน แต่มี HbA1c ติดตาม 95 คน อีก 1 คนไม่มีผลตรวจ':'จากผู้ใช้ยาตั้งต้น 808 คน ประเมินร่วมได้ 680 คน อีก 128 คนข้อมูลติดตามไม่ครบ';
  return result(G.waffle(r),title,`${denominator} • ผล ณ จุดติดตาม 6 เดือน* ยังยืนยัน remission ไม่ได้ เพราะไม่มีวันหยุดยาเพื่อยืนยันช่วงปลอดยา ≥ 3 เดือน`,[r],['remission_detail'],`n = ${r.n}`,`${title}: ${r.events}/${r.n} คน (${num(r.pct)}%)`);
 }},
 {id:'clinical',label:'ผลลัพธ์มากกว่าการหยุดยา',chapter:1,eyebrow:'04 / BEYOND MEDICATION',title:'ประโยชน์ที่เห็น<br>มีมากกว่า<br><em>การหยุดยา</em>',lead:'ดูผลก่อน–หลังในคนเดิมทั้งภาพรวม และแยกตาม HbA1c ตั้งต้นมากกว่า 6.5% กับไม่เกิน 6.5% เพื่อเห็นว่าทั้งระดับเริ่มต้นและการเปลี่ยนแปลงต่างกันเพียงใด',insight:'กลุ่มเริ่มต้นต่างกัน ความต่างของค่าเฉลี่ยยังรวม regression to the mean และปัจจัยกวน จึงยังไม่ใช่ผลเชิงสาเหตุของโครงการ',foot:'ภาพรวม: notebook 02 §4 · table2_paired_change.csv; มุมมองแยก HbA1c ตั้งต้น: table22_clinical_strata_m6.csv · paired change ที่จุดติดตาม 6 เดือน',controls:[select('metric','ตัวชี้วัด',metrics),select('population','กลุ่มที่แสดง',[['all','ภาพรวม'],['compare','เปรียบเทียบ HbA1c > 6.5% กับ ≤ 6.5%'],['gt65','HbA1c ตั้งต้น > 6.5%'],['le65','HbA1c ตั้งต้น ≤ 6.5%']])],render(T,s){
  const label={HbA1c:'HbA1c',FBS:'Fasting blood sugar',BMI:'BMI',Waist:'Waist circumference'}[s.metric];
  if(s.population==='all'){
   const r=T.changes.find(r=>r.measure===label&&r.definition==='At 6 months');
   return result(G.paired(r,label),`การเปลี่ยนแปลง ${s.metric} — ภาพรวม`,`*ฐานเวลาในคู่ข้อมูลนี้: ${timingText(r.tiers)} • เส้นเชื่อมแสดงค่าเฉลี่ยสองจุด ไม่ใช่เส้นทางระหว่างการติดตาม`,[r],['changes'],`n = ${r.n_pairs}`,`${s.metric} เปลี่ยนเฉลี่ย ${signed(r.mean_change)} ${units[s.metric]}, 95% CI ${signed(r.lo95)} ถึง ${signed(r.hi95)}`);
  }
  const rows=['gt65','le65'].map(group=>T.clinical_strata.find(r=>r.dimension==='baseline_hba1c'&&r.group===group&&r.measure===label));
  const note='HbA1c ตั้งต้น > 6.5%: 660 คน; ≤ 6.5%: 308 คน; ไม่ทราบค่าเริ่มต้น 27 คน • แต่ละตัวชี้วัดใช้เฉพาะคู่ข้อมูลครบ • เวลา 6 เดือนส่วนใหญ่อนุมานจากแบบบันทึก';
  if(s.population==='compare')return result(G.clinicalComparison(rows,s.metric),`${s.metric}: เปรียบเทียบตาม HbA1c ตั้งต้น`,note,rows,['clinical_strata'],'BASELINE HbA1c',`${s.metric} เปลี่ยน ${signed(rows[0].mean_change)} เทียบกับ ${signed(rows[1].mean_change)} ${units[s.metric]}`);
  const r=rows.find(r=>r.group===s.population),name=s.population==='gt65'?'> 6.5%':'≤ 6.5%';
  return result(G.paired(r,label),`${s.metric} — HbA1c ตั้งต้น ${name}`,`${note} • กลุ่มที่เลือก: ${timingText(r.tiers)}`,[r],['clinical_strata'],`n = ${r.n_pairs}`,`${s.metric} เปลี่ยนเฉลี่ย ${signed(r.mean_change)} ${units[s.metric]} ในกลุ่ม HbA1c ตั้งต้น ${name}`);
 }},
 {id:'subgroups',label:'จุดเริ่มต้นไม่เหมือนกัน',chapter:1,eyebrow:'05 / DIFFERENT STARTING POINTS',title:'คนละจุดเริ่มต้น<br>ควรมี<em>เป้าหมาย<br>ที่ต่างกันได้</em>',lead:'เปรียบเทียบผู้ที่ไม่ใช้ยาตั้งต้นและ HbA1c > 6.5% (G1 จำนวน 89 คน) กับผู้ใช้ยา (G2–G3) พร้อมแยก G2 ตามการใช้ insulin ตั้งต้น ชี้หรือแตะชื่อกลุ่มเพื่ออ่านนิยาม',insight:'การจัดบริการควรอิงความเสี่ยง ความพร้อม และเป้าหมายร่วม มากกว่ากำหนดให้ทุกคนต้องหยุดยา',foot:'กลุ่มที่ปรับนิยาม: G1 ไม่ใช้ยาตั้งต้นและ HbA1c > 6.5% (89 คน), G2 ใช้ยาและ HbA1c ≥ 6.5% (564 คน), G3 ใช้ยาและ HbA1c < 6.5% (229 คน) รวม 882 คน; อีก 113 คนไม่อยู่ในกลุ่มที่แสดงหรือข้อมูลไม่ครบ · คำนวณ paired change ใหม่จากแหล่งข้อมูลเดียวกับ notebook 02',controls:[select('metric','ตัวชี้วัด',metrics),select('grouping','การแบ่งกลุ่ม',[['main','G1–G3'],['insulin','แยก G2 ตามการใช้ insulin']])],render(T,s){
  const label={HbA1c:'HbA1c',FBS:'Fasting blood sugar',BMI:'BMI',Waist:'Waist circumference'}[s.metric];
  const main=group=>T.clinical_strata.find(r=>r.dimension==='subgroup'&&r.group===group&&r.measure===label);
  const rows=s.grouping==='insulin'?[main('g1'),...['non_insulin','insulin'].map(group=>T.clinical_strata.find(r=>r.dimension==='g2_insulin'&&r.group===group&&r.measure===label)),main('g3')]:['g1','g2','g3'].map(main);
  const note=`หน่วย: ${units[s.metric]} • G1 ปรับเป็น HbA1c > 6.5%; G2–G3 คงเกณฑ์ ≥ 6.5% / < 6.5% ตามเดิม • ${s.grouping==='insulin'?'G2: ไม่ใช้ insulin 537 คน; ใช้ insulin 27 คน จึงมีความไม่แน่นอนสูง':'ค่าเฉลี่ยก่อน–หลังและ 95% CI ยังไม่ปรับปัจจัยกวน'}`;
  return result(G.subgroup(rows),`การเปลี่ยนแปลง ${s.metric} แยกตามจุดเริ่มต้น`,note,rows,['clinical_strata','group_metadata'],s.grouping==='insulin'?'G2 BY INSULIN':'3 GROUPS');
 }},
 {id:'determinants',label:'ใครมีแนวโน้มหยุดยา',chapter:1,eyebrow:'05 / WHO IS MORE LIKELY?',title:'น้ำตาลเริ่มต้น<br>และภาระยา<br><em>สัมพันธ์กับโอกาส</em>',lead:'ในแบบจำลองที่ปรับตัวแปรร่วมและคำนึงถึงการกระจุกตามหน่วยบริการ HbA1c ที่สูงขึ้นและจำนวนกลุ่มยาที่มากขึ้นสัมพันธ์กับ odds ของการหยุดยาที่ต่ำลง',insight:'ใช้หลักฐานเพื่อวางแผนการสนับสนุน ไม่ใช้โอกาสสำเร็จต่ำเป็นเหตุผลในการตัดคนออกจากบริการ',foot:'Notebook 02 §7 · GEE logistic แบบ exchangeable จัดกลุ่มตามหน่วยบริการ · aOR เป็น odds ratio ไม่ใช่ risk ratio',controls:[select('model','แบบจำลอง',[['A','A · ข้อมูลเริ่มต้น'],['B','B · เพิ่มการเปลี่ยนแปลง 6 เดือน']]),checkbox('ci','เส้น 95% CI')],render(T,s){const rows=T.models.filter(r=>r.model.startsWith(s.model));return result(G.forest(rows,s.ci),'ปัจจัยที่สัมพันธ์กับการหยุดยาที่ 6 เดือน','สเกล logarithmic • เส้นตั้ง aOR = 1 คือไม่มีความสัมพันธ์ • แบบจำลองนี้แสดงความสัมพันธ์ ไม่ใช่เครื่องมือทำนายเพื่อใช้รักษารายบุคคล',rows,['models'],'ADJUSTED OR');}},
 {id:'sites',label:'บริบทพื้นที่มีความหมาย',chapter:1,eyebrow:'06 / PLACE MATTERS',title:'ผลลัพธ์ต่างกัน<br><em>ระหว่างพื้นที่</em>',lead:'ค่าเฉลี่ยทั้งโครงการซ่อนความหลากหลายของผู้ป่วย รูปแบบบริการ และการบันทึกข้อมูล การอ่านความต่างจึงต้องมองขนาดกลุ่มและความไม่แน่นอนด้วย',insight:'ความต่างเป็นจุดตั้งต้นเพื่อเรียนรู้ร่วมกัน ยังใช้เป็นอันดับคุณภาพของหน่วยบริการไม่ได้',foot:'Notebook 02 §5.1 · table5_cessation_by_site.csv · ตารางเดิมแสดงเฉพาะพื้นที่ที่มีผู้เข้าเกณฑ์อย่างน้อย 8 คน',controls:[select('min','ขนาดกลุ่ม',[['8','ทุกพื้นที่ในตาราง (n ≥ 8)'],['20','เฉพาะ n ≥ 20'],['40','เฉพาะ n ≥ 40']]),select('sort','เรียงตาม',[['rate','สัดส่วนหยุดยา'],['size','จำนวนผู้เข้าเกณฑ์']]),checkbox('ci','เส้น 95% CI')],render(T,s){const rows=T.sites.filter(r=>r.n>=Number(s.min)).sort((a,b)=>s.sort==='size'?b.n-a.n:b.k/b.n-a.k/a.n);return result(G.sites(rows,s.ci),'สัดส่วนหยุดยา แยกตามหน่วยบริการ',`แสดง ${rows.length} พื้นที่ • เส้นประคือค่าโครงการรวม 13.4% (96/718) • จุดคำนวณจาก k/n; CI ใน CSV ปัดไว้ 3 ตำแหน่ง`,rows,['sites'],`${rows.length} SITES`);}},
 {id:'comparison',label:'เทียบกันบนเวลาเดียวกัน',chapter:1,eyebrow:'07 / THE SAME CLOCK',title:'เปลี่ยนกรอบเวลา<br><em>ข้อสรุปก็เปลี่ยน</em>',lead:'เมื่อใช้จุดติดตาม 6 เดือนร่วมกัน ความต่างของ HbA1c ระหว่างโครงการกับทะเบียนลดลงมาก ส่วนความต่างของน้ำตาลอดอาหารยังเห็นได้ชัด',insight:'ลองสลับ “ค่าล่าสุด” กับ “6 เดือน” เพื่อเห็นว่าช่วงเวลาติดตามมีผลต่อเรื่องที่เรากำลังเล่าอย่างไร',foot:'Notebook 02 §10 · table16_between_cohort_difference.csv · Welch’s t-test บน change scores ยังไม่ได้ปรับปัจจัยกวน',controls:[select('metric','ตัวชี้วัด',metrics.slice(0,2)),select('anchor','จุดติดตาม',[['6 months','6 เดือน — หลัก'],['last observed','ค่าล่าสุด — นิยามเดิม']])],render(T,s){const r=T.comparison.find(r=>r.measure===s.metric&&r.anchor===s.anchor);return result(G.compare(r),`${s.metric}: ${s.anchor==='6 months'?'จุดติดตาม 6 เดือนร่วมกัน':'ค่าที่บันทึกครั้งล่าสุด'}`,s.anchor==='6 months'?'กลุ่มทะเบียนมาจากโรงพยาบาลเดียวและบริบทต่างจากโครงการ • เวลาโครงการส่วนหนึ่งอนุมาน • การเทียบนี้ยังสรุปเหตุและผลไม่ได้':'เวลาติดตามต่างกันระหว่าง cohort • มุมมองนิยามเดิมเพื่อแสดงความไวของข้อสรุป ไม่ใช้เป็นผลเปรียบเทียบหลัก',[r],['comparison'],s.anchor==='6 months'?'6 MONTHS':'LAST OBSERVED');}},
 {id:'provider',label:'ยังตัดสินระดับบริการไม่ได้',chapter:1,eyebrow:'08 / READ THE DIFFERENCE CAREFULLY',title:'ตัวเลขต่างกัน<br>ยังตอบไม่ได้ว่า<br><em>ระดับไหนดีกว่า</em>',lead:'ปฐมภูมิมีอัตราหยุดยาดิบสูงกว่า แต่ระดับบริการเกือบซ้อนทับกับชนิดแบบบันทึก เมื่อดูเฉพาะแบบ CRF กลุ่มปฐมภูมิเหลือเพียง 41 คน',insight:'ข้อมูลชุดนี้ยังแยกผลของระดับบริการออกจากแบบบันทึกไม่ได้ การใช้แบบข้อมูลร่วมจึงเป็นเงื่อนไขของการประเมินครั้งต่อไป',foot:'Notebook 02 §5.2 · table17b และ table17c · ช่วงความเชื่อมั่น 95% แบบ Wilson',controls:[select('sample','ข้อมูลที่ใช้',[['all','ทุกแบบบันทึก'],['crf','เฉพาะแบบ CRF']]),checkbox('ci','เส้น 95% CI')],render(T,s){const key=s.sample==='crf'?'providers_crf':'providers';return result(G.provider(T[key],s.ci),'อัตราหยุดยา แยกตามระดับบริการ',s.sample==='crf'?'เฉพาะ CRF: ปฐมภูมิ 7/41 คน จาก 2 แห่ง; Fisher p = 0.167 • กลุ่มเล็ก ผลยังไม่ชัดเจน ไม่ได้ยืนยันว่าเท่ากัน':'ทุกแบบ: โรงพยาบาลชุมชน 40/426 คน; ปฐมภูมิ 56/292 คน • ความต่างดิบปนกับแบบบันทึกและบริบทผู้ป่วย',T[key],[key],s.sample==='crf'?'CRF ONLY':'ALL TEMPLATES');}},
 {id:'costs',label:'ค่ายาลด งานดูแลไม่ลด',chapter:2,eyebrow:'09 / PAY FOR CONTINUITY',title:'ค่ายาลดลง<br>แต่การดูแล<br><em>ยังต้องลงทุน</em>',lead:'ในทะเบียนบ้านตาขุน กลุ่มที่หยุดยามีค่ายาเฉลี่ยต่อครั้งลดลง ขณะที่ค่าตรวจทางห้องปฏิบัติการเพิ่มขึ้น การลดภาระยาจึงไม่ได้แปลว่าต้นทุนทุกด้านจะลดตาม',insight:'ระบบการจ่ายควรรองรับการติดตามและผลลัพธ์ระหว่างทาง ไม่ผูกคุณค่าทั้งหมดไว้กับการหยุดยา',foot:'Notebook 02 §8 · table14_cost_by_cessation.csv · ค่าใช้จ่ายต่อครั้งในกลุ่มทะเบียน ใช้นิยามหยุดยาครั้งล่าสุด',controls:[select('group','กลุ่ม',[['Stopped all drugs','หยุดยาลดน้ำตาลแล้ว'],['Still on drugs','ยังใช้ยาลดน้ำตาล']]),select('view','มุมมอง',[['means','ค่าเฉลี่ยก่อน–หลัง'],['paired','การเปลี่ยนแปลงแบบจับคู่']])],render(T,s){const r=T.costs.find(r=>r.group===s.group);return result(G.costs(r,s.view),'ค่ายาและค่าตรวจทางห้องปฏิบัติการ · บาท/ครั้ง',s.view==='means'?'ค่าเฉลี่ยก่อนและหลังใช้ข้อมูลที่มีในแต่ละช่วง จึงหักลบแทน paired change ไม่ได้ • ค่ายารวมทุกโรค • n คือขนาดกลุ่ม ไม่ใช่จำนวนคู่ต้นทุน':'การเปลี่ยนแปลงคำนวณจากคู่ข้อมูลของแต่ละหมวด จึงต่างจากผลลบค่าเฉลี่ยก่อน–หลัง • ผลรวมเป็นผลบวกสองหมวด ไม่ใช่ต้นทุนรวมของบริการ',[r],['costs'],`GROUP n = ${r.n}`);}},
 {id:'timing',label:'ข้อมูลที่ระบบยังขาด',chapter:2,eyebrow:'10 / BUILD THE INFORMATION BACKBONE',title:'วันที่สำคัญ<br><em>พอ ๆ กับตัวเลข</em>',lead:'รู้ว่าค่าน้ำตาลเท่าไรยังไม่พอ เราต้องรู้ว่าวัดเมื่อไร หยุดยาเมื่อไร และติดตามต่อเนื่องนานเท่าไร จึงจะประเมินผลได้ตรงคำถาม',insight:'ชุดข้อมูลร่วมควรบันทึกวันเริ่มโครงการ วันหยุดยา และวันตรวจ พร้อมนำข้อมูลกลับไปใช้ในการดูแล',foot:'Notebook 02 §3 · table15_timing_coverage.csv · ร่างนโยบายประเด็น 6 ระบบข้อมูลเพื่อบริการและการเรียนรู้',controls:[select('cohort','ชุดข้อมูล',[['program','กลุ่มโครงการ'],['registry','กลุ่มทะเบียน']])],render(T,s){const rows=T.timing.filter(r=>r.cohort===s.cohort);return result(G.timing(rows),'ที่มาของกรอบเวลา 6 เดือนในแต่ละตัวชี้วัด',s.cohort==='program'?'ตัวหารคือข้อมูลติดตามที่มีในแต่ละตัวชี้วัด ไม่ใช่จำนวน complete pairs หรือผู้เข้าเกณฑ์หยุดยา • HbA1c และข้อมูลยาส่วนใหญ่อยู่ในกลุ่มอนุมาน':'ทะเบียนมีวันตรวจ แต่ข้อมูลยาไม่มีวันที่ จึงไม่มีผลหยุดยาที่ 6 เดือน • วันที่ตรวจยอมรับในช่วง ±3 เดือนรอบเป้าหมาย',rows,['timing'],s.cohort==='program'?'PROGRAMME':'REGISTRY');}},
 {id:'policy',label:'ข้อเสนอเชิงระบบ 7 เรื่อง',chapter:2,eyebrow:'11 / SEVEN SYSTEM PRIORITIES',title:'จากข้อค้นพบ<br>สู่<em>ข้อเสนอ<br>เชิงระบบ 7 เรื่อง</em>',lead:'ร่างข้อเสนอจากการสัมภาษณ์ 9 พื้นที่เชื่อมสิ่งที่เกิดขึ้นกับผู้ป่วย เข้ากับบริการ ทีมงาน การจ่าย ข้อมูล และเงื่อนไขชีวิต',insight:'แต่ละข้อทำงานร่วมกัน เลือกประเด็นเพื่อดูสาระสำคัญ ผู้ร่วมขับเคลื่อน และจุดเริ่มต้นของการลงมือ',foot:'สังเคราะห์จาก (draft) policy recommendation.docx ประเด็น 1–7 · แผนภาพข้อเสนอ ไม่ใช่ผลเชิงปริมาณ',controls:[select('policy','ประเด็น',policies.map((p,i)=>[String(i),`${i+1}. ${p.short}`]))],render(T,s){const p=policies[Number(s.policy)];return result(G.policy(Number(s.policy)),`ข้อเสนอ ${Number(s.policy)+1} · ${p.short}`,'สาระย่อเพื่ออภิปรายจากร่างข้อเสนอ • รายชื่อผู้ร่วมขับเคลื่อนเป็นการจัดกลุ่มบทบาท ไม่มีการกำหนดภาระผูกพันหรืออนุมัตินโยบาย',[{ประเด็น:Number(s.policy)+1,หัวข้อ:p.short,เป้าหมาย:p.title,สาระ:p.body.join(' / '),ผู้ร่วมขับเคลื่อน:p.owner,เริ่มต้น:p.action}],['policy'],`POLICY 0${Number(s.policy)+1}`);}},
 {id:'pathway',label:'เส้นทางที่ไม่ทิ้งใครไว้',chapter:2,eyebrow:'12 / A PATHWAY THAT KEEPS PEOPLE IN',title:'ปรับความเข้มข้น<br><em>โดยไม่ตัดสิทธิ<br>การสนับสนุน</em>',lead:'เส้นทางบริการควรเปลี่ยนตามความเสี่ยง ความพร้อม และชีวิตของผู้ป่วย เชื่อมการดูแลใกล้บ้านกับทีมที่พร้อมรับความซับซ้อน',insight:'การกลับมาใช้ยาคือข้อมูลเพื่อปรับการดูแล ไม่ใช่ความล้มเหลวของผู้ป่วย การติดตามต้องไปต่อได้ทุกระดับ',foot:'แผนภาพสังเคราะห์เพื่อหารือจากร่างนโยบายประเด็น 2–3 และ 7 · ไม่ใช่เกณฑ์คัดกรองหรือคำแนะนำการปรับยา',controls:[select('level','เน้นระดับ',[['all','แสดงทุกระดับ'],['0','การสนับสนุนพื้นฐาน'],['1','การดูแลเข้มข้น'],['2','การดูแลซับซ้อน']])],render(T,s){return result(G.pathway(s.level),'เส้นทางบริการหลายระดับที่เชื่อมถึงกัน','ภาพแนวคิดบริการ: ทุกระดับมีการตัดสินใจร่วมและการติดตาม • ต้องพัฒนาเกณฑ์ความปลอดภัยและบทบาทจริงร่วมกับทีมบริการ',[{ระดับ:'พื้นฐาน',จุดเน้น:'ทุกคนเข้าถึงบริการและตกลงเป้าหมายร่วมกัน'},{ระดับ:'เข้มข้น',จุดเน้น:'เพิ่มการสนับสนุนตามความพร้อมและความเสี่ยง'},{ระดับ:'ซับซ้อน',จุดเน้น:'เชื่อมโรงพยาบาลและผู้เชี่ยวชาญตามข้อบ่งชี้ด้านความปลอดภัย'}],['policy'],'SERVICE DESIGN');}},
 {id:'next',label:'สร้างระบบ แล้วขยายโอกาส',chapter:2,eyebrow:'13 / THE NEXT CHAPTER',title:'ขยาย<em>โอกาส</em><br>พร้อมสร้างระบบ<br>ที่<em>ไปต่อได้</em>',lead:'หลักฐานชี้ถึงความเป็นไปได้ของการลดภาระยา แต่การขยายผลต้องลงทุนพร้อมกันในคุณภาพบริการ ความต่อเนื่องของทีม ข้อมูล และความเป็นธรรม',insight:'คำถามสำหรับการตัดสินใจ: จะทำให้การดูแลที่ดีอยู่ได้ในระบบประจำ และเข้าถึงคนที่มีข้อจำกัดมากขึ้นได้อย่างไร',foot:'ข้อสังเคราะห์เพื่ออภิปรายจาก notebook 02 และร่างนโยบายทั้ง 7 ประเด็น · ลำดับการขับเคลื่อนนี้เป็นข้อเสนอของสไลด์ฉบับร่าง',controls:[select('focus','เน้นช่วง',[['all','ภาพรวม'],['0','วางฐานร่วม'],['1','ทดลองให้ครบระบบ'],['2','เรียนรู้แล้วขยาย']])],render(T,s){return result(G.roadmap(s.focus),'สามจังหวะสู่การดูแลที่ต่อเนื่องและเป็นธรรม','เริ่มจากมาตรฐานร่วม ทดลองระบบบริการและการจ่าย แล้วใช้ผลลัพธ์ ความปลอดภัย ต้นทุน และการเข้าถึงประกอบการขยายผล',[{ลำดับ:1,จุดเน้น:'วางฐานร่วม',สิ่งที่ต้องทำ:'มาตรฐานบริการ นิยามผลลัพธ์ และชุดข้อมูลขั้นต่ำ'},{ลำดับ:2,จุดเน้น:'ทดลองให้ครบระบบ',สิ่งที่ต้องทำ:'เส้นทางบริการ กำลังคน เครือข่าย และการจ่ายแบบผสม'},{ลำดับ:3,จุดเน้น:'เรียนรู้แล้วขยาย',สิ่งที่ต้องทำ:'ติดตามผลระยะยาว ความปลอดภัย และความเป็นธรรม'}],['policy','notebook'],'DISCUSSION DRAFT');}}
];
export const chapters=['จุดตั้งต้น','สิ่งที่ข้อมูลบอกเรา','จากหลักฐานสู่นโยบาย'];
